---


- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Reload varnish
  systemd:
    name: varnish
    state: reloaded

- name: Restart varnish
  systemd:
    name: varnish
    state: restarted

- name: Restart varnish_exporter
  systemd:
    name: varnish_exporter
    state: restarted
