---

- name: Ensure HAProxy PPA is setup
  apt_repository:
    repo: "ppa:vbernat/haproxy-{{ haproxy__ppa_version }}"
    state: present
  when: haproxy__from_ppa|bool

- name: Ensure HAProxy and socat are installed
  apt:
    name:
      - haproxy
      - socat
    state: latest
  tags:
    - skip_ansible_lint

- name: Ensure {{ haproxy__ssl_dir }} directory exists
  file:
    path: "{{ haproxy__ssl_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Ensure dh-param file exists
  shell: openssl dhparam 2048 >{{ haproxy__ssl_dir }}/dh-param.pem
  args:
    creates: "{{ haproxy__ssl_dir }}/dh-param.pem"

- name: Ensure HAProxy configuration directory exists
  file:
    path: /etc/haproxy/conf.d
    state: directory

- name: Ensure HAProxy is configured
  template:
    src: "{{ item }}.j2"
    dest: /etc/haproxy/conf.d/{{ item }}
  with_items:
    - 00_global_defaults.cfg
    - 10_stats.cfg

- name: Assemble HAProxy configuration
  assemble:
    src: /etc/haproxy/conf.d
    dest: /etc/haproxy/haproxy.cfg
    validate: 'haproxy -c -f %s'
  notify: Reload HAProxy

- name: Check whether check_mk is installed
  stat:
    path: "{{ cmk_usr_dir }}"
  changed_when: false
  register: cmk_path

- name: Ensure mk_haproxy is installed
  copy:
    src: mk_haproxy
    dest: "{{ cmk_usr_dir }}/plugins/mk_haproxy"
    owner: root
    group: root
    mode: 0755
  when: cmk_path.stat.exists
