---
- name: Ensure Docker release key is present in APT keyring
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: Ensure stable Docker Ubuntu APT repository has been set up
  apt_repository:
    repo: >
      deb
      [arch={{ (ansible_architecture == 'x86_64')
      | ternary('amd64', ansible_architecture) }}]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: true

- name: Ensure docker-ce, python bindings and pip are installed
  apt:
    name:
      - docker-ce
      - pass  # workaround for
      # https://bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119
      - python-docker
      - python3-docker
      - python3-pip
      - python3-setuptools
    state: present

- name: Ensure mk_docker.py is installed
  copy:
    src: mk_docker.py
    dest: "{{ cmk_usr_dir }}/plugins/mk_docker.py"
    owner: root
    group: root
    mode: 0755
  when: cmk_path.stat.exists
