---

- name: Ensure docker.io, python bindings are installed
  apt:
    name:
      - docker.io
      - python3-docker
      - python3-pip
      - python3-setuptools
    state: present

- name: Ensure docker-compose is installed
  pip:
    name: docker-compose
    state: present

- name: Ensure mk_docker.py is installed
  copy:
    src: mk_docker.py3
    dest: "{{ cmk_usr_dir }}/plugins/mk_docker.py"
    owner: root
    group: root
    mode: 0755
  when: cmk_path.stat.exists
