---
- name: Ensure Docker release key is present in APT keyring
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: Ensure stable Docker Ubuntu APT repository has been set up
  apt_repository:
    repo: >
      deb
      [arch={{ (ansible_architecture == 'x86_64')
      | ternary('amd64', ansible_architecture) }}]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: true

- name: Ensure docker-ce and pip are installed
  apt:
    name:
      - docker-ce
      - python3-pip
      - python3-setuptools
    state: present

- name: Ensure docker-compose is installed
  pip:
    name: docker-compose
    state: present

- name: Ensure localhost docker network exists
  docker_network:
    name: localhost
    driver: bridge
    ipam_config:
      - subnet: '10.127.0.0/16'
        gateway: '10.127.0.1'
