---

- name: Check whether check_mk is installed
  stat:
    path: "{{ cmk_usr_dir }}"
  changed_when: false
  register: cmk_path

- include_tasks: bionic.yml
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int <= 18

- include_tasks: focal.yml
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int > 18

- name: Ensure docker-compose is installed
  pip:
    name: docker-compose
    state: present

- name: Ensure localhost docker network exists
  docker_network:
    name: localhost
    driver: bridge
    ipam_config:
      - subnet: '10.127.0.0/16'
        gateway: '10.127.0.1'

- name: Ensure mk_docker_node is removed
  file:
    state: absent
    path: "{{ cmk_usr_dir }}/plugins/mk_docker_node"
