---

- name: Ensure oauth2_proxy group exists
  group:
    name: oauth2_proxy
    state: present

- name: Ensure oauth2_proxy user exists
  user:
    name: oauth2_proxy
    shell: /usr/sbin/nologin
    group: oauth2_proxy

- name: Install oauth2_proxy
  get_url:
    url: "{{ oauth2_proxy_url }}"
    checksum: sha256:{{ oauth2_proxy__binary_sha256sum }}
    dest: /usr/local/bin/oauth2_proxy
    owner: root
    group: root
    mode: 0755
  register: get_url_status
  until: get_url_status is succeeded
  notify:
    - Restart oauth2_proxy

- name: Ensure oauth2_proxy service exists
  copy:
    src: oauth2_proxy.service
    dest: /etc/systemd/system/oauth2_proxy.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
