#!/usr/bin/env python

import subprocess

status_code = 0
status_message = 'no updates'

try:
  output = subprocess.check_output(['/usr/lib/update-notifier/apt-check'], stderr=subprocess.STDOUT)
  total, security = output.split(';')
  total = int(total)
  security = int(security)
  if total > 0:
    status_code = 1
    status_message = '%s updates pending' % total
  if security > 0:
    status_code = 2
    status_message = '%s security updates pending' % total
except Exception as exc:
  status_code = 3
  status_message = exc

print('%i APT_Check - %s' % (status_code, status_message))
