---

- name: Ensure certbot PPA is configured
  apt_repository:
    state: present
    repo: 'ppa:certbot/certbot'
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int < 20

- name: Ensure certbot is installed
  apt:
    state: present
    name: certbot
