---

- name: Find cloud-init file
  find:
    paths: /etc/ssh/sshd_config.d
    patterns: "*cloud-init.conf"
  register: cloud_init_to_delete

- name: Remove cloud-init sshd config file
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ cloud_init_to_delete.files }}"

- name: Install secure sshd_config
  copy:
    src: sshd_config__{{ ansible_lsb.codename }}
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Reload sshd

- name: Disable cloud-init management of /etc/hosts
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^ - update_etc_hosts'
    state: absent

- name: Install /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: not inventory_hostname|ipaddr

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname|ipaddr

- name: Decrease dhclient timeout
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    regexp: '^timeout.*$'
    line: 'timeout 10;'

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Ensure setfacl is installed
  package:
    state: present
    name: acl
